export enum DbConnectivity {
  DB_CONNECTIVITY = 'DB_CONNECTIVITY',
}

export enum ServiceTags {
  CLIENT_PROFILE_SERVICE = 'CLIENT_PROFILE_SERVICE',
  CAREGIVER_PROFILE_SERVICE = 'CAREGIVER_PROFILE_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
  ROLE_SERVICE = 'ROLE_SERVICE',
  ADDRESS_SERVICE = 'ADDRESS_SERVICE',
  BOOKINGS_SERVICE = 'BOOKINGS_SERVICE',
  EMAIL_SERVICE = 'EMAIL_SERVICE',
  SMS_SERVICE = 'SMS_SERVICE',
  CHAT_SERVICE = 'CHAT_SERVICE',
  TWILIO_SERVICE = 'TWILIO_SERVICE',
  VOICE_CALL_SERVICE = 'VOICE_CALL_SERVICE',
  NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
  FIREBASE_SERVICE = 'FIREBASE_SERVICE',
  REVIEW_SERVICE = 'REVIEW_SERVICE',
  AWS_S3_SERVICE = 'AWS_S3_SERVICE',
}
